Rails.application.config.assets.precompile += %w( manage.css  manage.js )
Rails.application.config.assets.paths << Rails.root.join("app", "assets", "fonts")
Rails.application.config.assets.precompile += %w( login_page.js )
Rails.application.config.assets.precompile += %w( login_page.css )
Rails.application.config.assets.precompile += %w( setting_page.js )
Rails.application.config.assets.precompile += %w( account.js account.css )
Rails.application.config.assets.precompile += %w( job_show.js )
Rails.application.config.assets.precompile += %w( embed.css embed.js )
Rails.application.config.assets.precompile += %w( report.js )
Rails.application.config.assets.precompile += %w( respond.min.js )
Rails.application.config.assets.precompile += %w( report.css )
Rails.application.config.assets.precompile += %w( opportunity.css )
Rails.application.config.assets.precompile += %w( success_payment.css )
Rails.application.config.assets.precompile += %w( createInvoiceValidate.js )
Rails.application.config.assets.precompile += %w( getInvoiceSms.js )
Rails.application.config.assets.precompile += %w( swimming-lesson-registration.js )
Rails.application.config.assets.precompile += %w( cannedResponse.js )
Rails.application.config.assets.precompile += %w( instructor-public-profile.js )
Rails.application.config.assets.precompile += %w( instructor-public-profile.css )
Rails.application.config.assets.precompile += %w( multiple_message_send_script.js )
Rails.application.config.assets.precompile += %w( dashboardDaterange.js )
Rails.application.config.assets.precompile += %w( manage/table-managed.js )
Rails.application.config.assets.precompile += %w( paymentMethod.js )
Rails.application.config.assets.precompile += %w( jobs.js )
Rails.application.config.assets.precompile += %w( manage/jquery.mobile-1.4.5.js )
Rails.application.config.assets.precompile += %w( manage/jquery.mobile-1.4.5.css )
Rails.application.config.assets.precompile += %w( video-js.swf vjs.eot vjs.svg vjs.ttf vjs.woff )
%w( instructor/instructor_profile ).each do |controller|
  Rails.application.config.assets.precompile += ["#{controller}.js", "#{controller}.css"]
end