# ReddotCredential.create(:name => "MasterCard", :url => "https://connect.reddotpayment.com/instanpanel", :merchant_id =>  "0000021303", :key => "28a3dfd6da82c5c004cde3c23b68ca85335bf9d9")
# ReddotCredential.create(:name => "Enets", :url => "https://connect.reddotpayment.com/instanpanel", :merchant_id =>  "0000021305", :key => "584c331b96a9498c45c1473f6c1204df152a34a4")

# AgeGroup.create(:title => "Preschool")
# AgeGroup.create(:title => "Kids")
# AgeGroup.create(:title => "Adult")

# RegistrationPackage.create(no_of_student: 1, is_lady: false, age_group_id: 2, price: 240)
# RegistrationPackage.create(no_of_student: 1, is_lady: false, age_group_id: 3, price: 240)
# RegistrationPackage.create(no_of_student: 2, is_lady: false, age_group_id: 2, price: 270)
# RegistrationPackage.create(no_of_student: 2, is_lady: false, age_group_id: 3, price: 270)
# RegistrationPackage.create(no_of_student: 3, is_lady: false, age_group_id: 2, price: 300)
# RegistrationPackage.create(no_of_student: 3, is_lady: false, age_group_id: 3, price: 300)
# RegistrationPackage.create(no_of_student: 4, is_lady: false, age_group_id: 2, price: 330)
# RegistrationPackage.create(no_of_student: 4, is_lady: false, age_group_id: 3, price: 330)


# RegistrationPackage.create(no_of_student: 1, is_lady: true, age_group_id: 2, price: 350)
# RegistrationPackage.create(no_of_student: 1, is_lady: true, age_group_id: 3, price: 350)
# RegistrationPackage.create(no_of_student: 2, is_lady: true, age_group_id: 2, price: 400)
# RegistrationPackage.create(no_of_student: 2, is_lady: true, age_group_id: 3, price: 400)
# RegistrationPackage.create(no_of_student: 3, is_lady: true, age_group_id: 2, price: 450)
# RegistrationPackage.create(no_of_student: 3, is_lady: true, age_group_id: 3, price: 450)
# RegistrationPackage.create(no_of_student: 4, is_lady: true, age_group_id: 2, price: 500)
# RegistrationPackage.create(no_of_student: 4, is_lady: true, age_group_id: 3, price: 500)


# Level.create(:title => "Beginner")
# Level.create(:title => "Swimmer")

# ClassType.create! :title => "Group"
# ClassType.create! :title => "Private"

# MessageTemplate.create(:job_status => "post")
# MessageTemplate.create(:job_status => "suggest")
# MessageTemplate.create(:job_status => "invoice")
# MessageTemplate.create(:job_status => "receipt")
# MessageTemplate.create(:job_status => "invoice_note")
# MessageTemplate.create(:job_status => "payment_advise")
# MessageTemplate.create(:job_status => "invoice_pa")


# puts "Please wait Venue are being loaded.."
#   Venue.create! :name =>"Ang Mo Kio Swimming Complex"
#   Venue.create! :name =>"Bedok Swimming Complex"
#   Venue.create! :name =>"Bishan Swimming Complex"
#   Venue.create! :name =>"Bukit Batok Swimming Complex"
#   Venue.create! :name =>"Bukit Timah Swimming Complex"
#   Venue.create! :name =>"Buona Vista Swimming Complex"
#   Venue.create! :name =>"Clementi Swimming Complex"
#   Venue.create! :name =>"Choa Chu Kang Swimming Complex"
#   Venue.create! :name =>"Delta Swimming Complex"
#   Venue.create! :name =>"Geylang East Swimming Complex"
#   Venue.create! :name =>"Jalan Besar Swimming Complex"
#   Venue.create! :name =>"Jurong East Swimming Complex"
#   Venue.create! :name =>"Jurong West Swimming Complex"
#   Venue.create! :name =>"Kallang Basin Swimming Complex"
#   Venue.create! :name =>"Katong Swimming Complex"
#   Venue.create! :name =>"Queenstown Swimming Complex"
#   Venue.create! :name =>"Sengkang Swimming Complex"
#   Venue.create! :name =>"Serangoon Swimming Complex"
#   Venue.create! :name =>"Tampines Swimming Complex"
#   Venue.create! :name =>"Toa Payoh Swimming Complex"
#   Venue.create! :name =>"Woodlands Swimming Complex"
#   Venue.create! :name =>"Yio Chu Kang Swimming Complex"
#   Venue.create! :name =>"Yishun Swimming Complex"
#   Venue.create! :name =>"Hougang Swimming Complex"
#   Venue.create! :name =>"Pasir Ris Swimming Complex"
#   Venue.create! :name =>"Condo"
# puts "Venues created successfully."

# puts "Please wait Instructors are being loaded.."
# Instructor.create! :name=> "Adrain",:mobile=> "97928819",:email => "97928819@singaporeswimming.com",:password => "password",:short_name => "Adrain",:gender => "Male"
# Instructor.create! :name=> "Alan Chan",:mobile=> "97109016",:email => "97109016@singaporeswimming.com",:password => "password",:short_name => "Alan Chan",:gender => "Male"
# Instructor.create! :name=> "Albert Kua (AMK)",:mobile=> "93826566",:email => "93826566@singaporeswimming.com",:password => "password",:short_name => "Albert Kua",:gender => "Male"
# Instructor.create! :name=> "Albert Teo",:mobile=> "92390008",:email => "92390008@singaporeswimming.com",:password => "password",:short_name => "Albert Teo",:gender => "Male"
# Instructor.create! :name=> "Alex Chan (Bishan LG)",:mobile=> "92390515",:email => "92390515@singaporeswimming.com",:password => "password",:short_name => "Alex Chan",:gender => "Male"
# Instructor.create! :name=> "Alex Chionh",:mobile=> "96806280",:email => "96806280@singaporeswimming.com",:password => "password",:short_name => "Alex Chionh",:gender => "Male"
# Instructor.create! :name=> "Alex Lee",:mobile=> "94748568",:email => "94748568@singaporeswimming.com",:password => "password",:short_name => "Alex Lee",:gender => "Male"
# Instructor.create! :name=> "Alex Loh",:mobile=> "96610104",:email => "96610104@singaporeswimming.com",:password => "password",:short_name => "Alex Loh",:gender => "Male"
# Instructor.create! :name=> "Alex Quek",:mobile=> "97998821",:email => "97998821@singaporeswimming.com",:password => "password",:short_name => "Alex Quek",:gender => "Male"
# Instructor.create! :name=> "Alex Zhang",:mobile=> "93666443",:email => "93666443@singaporeswimming.com",:password => "password",:short_name => "Alex Zhang",:gender => "Male"
# Instructor.create! :name=> "Alexy Yor",:mobile=> "91899696",:email => "91899696@singaporeswimming.com",:password => "password",:short_name => "Alexy",:gender => "Male"
# Instructor.create! :name=> "Alvin Choon",:mobile=> "98415011",:email => "98415011@singaporeswimming.com",:password => "password",:short_name => "Alvin Choon",:gender => "Male"
# Instructor.create! :name=> "Alvin Ong",:mobile=> "91055300",:email => "91055300@singaporeswimming.com",:password => "password",:short_name => "Alvin",:gender => "Male"
# Instructor.create! :name=> "Alvin Tan",:mobile=> "98634995",:email => "98634995@singaporeswimming.com",:password => "password",:short_name => "Alvin Tan",:gender => "Male"
# Instructor.create! :name=> "Andy Chua Meng Hong",:mobile=> "91777759",:email => "91777759@singaporeswimming.com",:password => "password",:short_name => "Andy Chua",:gender => "Male"
# Instructor.create! :name=> "Andy Ong",:mobile=> "92338969",:email => "92338969@singaporeswimming.com",:password => "password",:short_name => "Andy Ong",:gender => "Male"
# Instructor.create! :name=> "Angelina",:mobile=> "90499064",:email => "90499064@singaporeswimming.com",:password => "password",:short_name => "Angelina",:gender => "Male"
# Instructor.create! :name=> "Arfian",:mobile=> "90693177",:email => "90693177@singaporeswimming.com",:password => "password",:short_name => "Arfian",:gender => "Male"
# Instructor.create! :name=> "Arron Lam",:mobile=> "97394569",:email => "97394569@singaporeswimming.com",:password => "password",:short_name => "Arron Lam",:gender => "Male"
# Instructor.create! :name=> "Ben (serangoon)",:mobile=> "93400025",:email => "93400025@singaporeswimming.com",:password => "password",:short_name => "Ben (serangoon)",:gender => "Male"
# Instructor.create! :name=> "Ben Tham",:mobile=> "96261008",:email => "96261008@singaporeswimming.com",:password => "password",:short_name => "Ben Tham",:gender => "Male"
# Instructor.create! :name=> "Bernita",:mobile=> "96951975",:email => "96951975@singaporeswimming.com",:password => "password",:short_name => "Bernita",:gender => "Female"
# Instructor.create! :name=> "Bob Lim",:mobile=> "96316521",:email => "96316521@singaporeswimming.com",:password => "password",:short_name => "Bob Lim",:gender => "Male"
# Instructor.create! :name=> "Bobby Lau",:mobile=> "91095358",:email => "91095358@singaporeswimming.com",:password => "password",:short_name => "Bobby Lau",:gender => "Male"
# Instructor.create! :name=> "Chan Kok Hong",:mobile=> "97665968",:email => "97665968@singaporeswimming.com",:password => "password",:short_name => "Chan Kok Hong",:gender => "Male"
# Instructor.create! :name=> "Chan Yan Jun",:mobile=> "90043742",:email => "90043742@singaporeswimming.com",:password => "password",:short_name => "Chan Yan Jun",:gender => "Male"
# Instructor.create! :name=> "Chng Hock Guan",:mobile=> "90620682",:email => "90620682@singaporeswimming.com",:password => "password",:short_name => "Chng Hock Guan",:gender => "Male"
# Instructor.create! :name=> "Chong (Katong)",:mobile=> "96567461",:email => "96567461@singaporeswimming.com",:password => "password",:short_name => "Chong",:gender => "Male"
# Instructor.create! :name=> "Chong Wee",:mobile=> "94898962",:email => "94898962@singaporeswimming.com",:password => "password",:short_name => "Chong Wee",:gender => "Male"
# Instructor.create! :name=> "Chong(Clementi)",:mobile=> "96967239",:email => "96967239@singaporeswimming.com",:password => "password",:short_name => "Mr Chong",:gender => "Male"
# Instructor.create! :name=> "Chris Lee (Delta)",:mobile=> "94550644",:email => "94550644@singaporeswimming.com",:password => "password",:short_name => "Chris Lee",:gender => "Male"
# Instructor.create! :name=> "Christopher katong",:mobile=> "91133187",:email => "91133187@singaporeswimming.com",:password => "password",:short_name => "Christopher",:gender => "Male"
# Instructor.create! :name=> "Chua Liqi",:mobile=> "91808652",:email => "91808652@singaporeswimming.com",:password => "password",:short_name => "Chua Liqi",:gender => "Female"
# Instructor.create! :name=> "Clement",:mobile=> "90694220",:email => "90694220@singaporeswimming.com",:password => "password",:short_name => "Clement",:gender => "Male"
# Instructor.create! :name=> "Damien",:mobile=> "85111858",:email => "85111858@singaporeswimming.com",:password => "password",:short_name => "Damien",:gender => "Male"
# Instructor.create! :name=> "Daniel Ho",:mobile=> "90493497",:email => "90493497@singaporeswimming.com",:password => "password",:short_name => "Daniel Ho",:gender => "Male"
# Instructor.create! :name=> "Daniel Loo",:mobile=> "96332658",:email => "96332658@singaporeswimming.com",:password => "password",:short_name => "Daniel Loo",:gender => "Male"
# Instructor.create! :name=> "Darren Pang JE",:mobile=> "90400099",:email => "90400099@singaporeswimming.com",:password => "password",:short_name => "Darren Pang",:gender => "Male"
# Instructor.create! :name=> "Daryl CCK",:mobile=> "96863121",:email => "96863121@singaporeswimming.com",:password => "password",:short_name => "Daryl",:gender => "Male"
# Instructor.create! :name=> "David",:mobile=> "81114408",:email => "81114408@singaporeswimming.com",:password => "password",:short_name => "David",:gender => "Male"
# Instructor.create! :name=> "David Peh",:mobile=> "90606548",:email => "90606548@singaporeswimming.com",:password => "password",:short_name => "David Peh",:gender => "Male"
# Instructor.create! :name=> "Denis Tan",:mobile=> "92293138",:email => "92293138@singaporeswimming.com",:password => "password",:short_name => "Denis",:gender => "Male"
# Instructor.create! :name=> "Dennis Liam",:mobile=> "96942351",:email => "96942351@singaporeswimming.com",:password => "password",:short_name => "Dennis Liam",:gender => "Male"
# Instructor.create! :name=> "Derek Man",:mobile=> "91377619",:email => "91377619@singaporeswimming.com",:password => "password",:short_name => "Derek",:gender => "Male"
# Instructor.create! :name=> "Derrick Yeo Swee Keong",:mobile=> "96538285",:email => "96538285@singaporeswimming.com",:password => "password",:short_name => "Derrick Yeo",:gender => "Male"
# Instructor.create! :name=> "Desmond Ho",:mobile=> "96613608",:email => "96613608@singaporeswimming.com",:password => "password",:short_name => "Desmond Ho",:gender => "Male"
# Instructor.create! :name=> "Desmond Yong",:mobile=> "91078512",:email => "91078512@singaporeswimming.com",:password => "password",:short_name => "Desmond Yong",:gender => "Male"
# Instructor.create! :name=> "Dick Lee",:mobile=> "93873362",:email => "93873362@singaporeswimming.com",:password => "password",:short_name => "Dick Lee",:gender => "Male"
# Instructor.create! :name=> "Doris Low",:mobile=> "92767077",:email => "92767077@singaporeswimming.com",:password => "password",:short_name => "Doris Low",:gender => "Female"
# Instructor.create! :name=> "Eddy",:mobile=> "90268321",:email => "90268321@singaporeswimming.com",:password => "password",:short_name => "Eddy",:gender => "Male"
# Instructor.create! :name=> "Edmund (GE LG)",:mobile=> "94590084",:email => "94590084@singaporeswimming.com",:password => "password",:short_name => "Edmund (GE LG)",:gender => "Male"
# Instructor.create! :name=> "Edward Louise",:mobile=> "84913857",:email => "84913857@singaporeswimming.com",:password => "password",:short_name => "Edward Louise",:gender => "Male"
# Instructor.create! :name=> "Elangovan",:mobile=> "90921825",:email => "90921825@singaporeswimming.com",:password => "password",:short_name => "Elangovan",:gender => "Male"
# Instructor.create! :name=> "Elson Leong",:mobile=> "94879484",:email => "94879484@singaporeswimming.com",:password => "password",:short_name => "Elson Leong",:gender => "Male"
# Instructor.create! :name=> "Elvin Low",:mobile=> "96895751",:email => "96895751@singaporeswimming.com",:password => "password",:short_name => "Elvin Low",:gender => "Male"
# Instructor.create! :name=> "Elvin Yuen",:mobile=> "96513436",:email => "96513436@singaporeswimming.com",:password => "password",:short_name => "Elvin Yuen",:gender => "Male"
# Instructor.create! :name=> "Emily Sengkang",:mobile=> "92720296",:email => "92720296@singaporeswimming.com",:password => "password",:short_name => "Emily",:gender => "Female"
# Instructor.create! :name=> "Eric Koh",:mobile=> "96776067",:email => "96776067@singaporeswimming.com",:password => "password",:short_name => "Eric Koh",:gender => "Male"
# Instructor.create! :name=> "Eric Lee",:mobile=> "91812329",:email => "91812329@singaporeswimming.com",:password => "password",:short_name => "Eric Lee",:gender => "Male"
# Instructor.create! :name=> "Eric Shia",:mobile=> "97482840",:email => "97482840@singaporeswimming.com",:password => "password",:short_name => "Eric Shia",:gender => "Male"
# Instructor.create! :name=> "Eric Yen",:mobile=> "94502154",:email => "94502154@singaporeswimming.com",:password => "password",:short_name => "Eric Yen",:gender => "Male"
# Instructor.create! :name=> "Eryanto",:mobile=> "96160941",:email => "96160941@singaporeswimming.com",:password => "password",:short_name => "Eryanto",:gender => "Male"
# Instructor.create! :name=> "Fandi",:mobile=> "98147742",:email => "98147742@singaporeswimming.com",:password => "password",:short_name => "Fandi",:gender => "Male"
# Instructor.create! :name=> "Fish Gay Hui Ting",:mobile=> "96576466",:email => "96576466@singaporeswimming.com",:password => "password",:short_name => "Fish",:gender => "Female"
# Instructor.create! :name=> "Fran",:mobile=> "92211642",:email => "92211642@singaporeswimming.com",:password => "password",:short_name => "Fran",:gender => "Female"
# Instructor.create! :name=> "Francis Koh",:mobile=> "96972993",:email => "96972993@singaporeswimming.com",:password => "password",:short_name => "Francis Koh",:gender => "Male"
# Instructor.create! :name=> "Francis Ong",:mobile=> "81289968",:email => "81289968@singaporeswimming.com",:password => "password",:short_name => "Francis Ong",:gender => "Male"
# Instructor.create! :name=> "Francis Tay",:mobile=> "90237812",:email => "90237812@singaporeswimming.com",:password => "password",:short_name => "Francis Tay",:gender => "Male"
# Instructor.create! :name=> "Freddie Ang",:mobile=> "96655447",:email => "96655447@singaporeswimming.com",:password => "password",:short_name => "Freddie Ang",:gender => "Male"
# Instructor.create! :name=> "Freddie Har",:mobile=> "94554345",:email => "94554345@singaporeswimming.com",:password => "password",:short_name => "Freddie Har",:gender => "Male"
# Instructor.create! :name=> "Freddie Ng",:mobile=> "97725823",:email => "97725823@singaporeswimming.com",:password => "password",:short_name => "Freddie Ng",:gender => "Male"
# Instructor.create! :name=> "Gabriel",:mobile=> "92324273",:email => "92324273@singaporeswimming.com",:password => "password",:short_name => "Gabriel",:gender => "Male"
# Instructor.create! :name=> "Gan Boon Leong",:mobile=> "96998619",:email => "96998619@singaporeswimming.com",:password => "password",:short_name => "Gan Boon Leong",:gender => "Male"
# Instructor.create! :name=> "Gavin Tan",:mobile=> "82011616",:email => "82011616@singaporeswimming.com",:password => "password",:short_name => "Gavin Tan",:gender => "Male"
# Instructor.create! :name=> "Gerald Lau",:mobile=> "93380690",:email => "93380690@singaporeswimming.com",:password => "password",:short_name => "Gerald Lau",:gender => "Male"
# Instructor.create! :name=> "Gilbert",:mobile=> "98808217",:email => "98808217@singaporeswimming.com",:password => "password",:short_name => "Gilbert",:gender => "Male"
# Instructor.create! :name=> "Goh Hock Lye",:mobile=> "90010437",:email => "90010437@singaporeswimming.com",:password => "password",:short_name => "Goh Hock Lye",:gender => "Male"
# Instructor.create! :name=> "Guan Ki",:mobile=> "96356695",:email => "96356695@singaporeswimming.com",:password => "password",:short_name => "Guan Ki",:gender => "Male"
# Instructor.create! :name=> "Harvey Teo",:mobile=> "98555805",:email => "98555805@singaporeswimming.com",:password => "password",:short_name => "Harvey Teo",:gender => "Male"
# Instructor.create! :name=> "Heikal Mubarah",:mobile=> "83821491",:email => "83821491@singaporeswimming.com",:password => "password",:short_name => "Heikal Mubarah",:gender => "Male"
# Instructor.create! :name=> "Henry Tan Meng Siang",:mobile=> "94882236",:email => "94882236@singaporeswimming.com",:password => "password",:short_name => "Henry Tan",:gender => "Male"
# Instructor.create! :name=> "Herman",:mobile=> "90091982",:email => "90091982@singaporeswimming.com",:password => "password",:short_name => "Herman",:gender => "Male"
# Instructor.create! :name=> "Hester",:mobile=> "96843155",:email => "96843155@singaporeswimming.com",:password => "password",:short_name => "Hester",:gender => "Female"
# Instructor.create! :name=> "Ho Guan Qian",:mobile=> "96671684",:email => "96671684@singaporeswimming.com",:password => "password",:short_name => "Ho Guan Qian",:gender => "Male"
# Instructor.create! :name=> "Ho Hock Siang",:mobile=> "92218630",:email => "92218630@singaporeswimming.com",:password => "password",:short_name => "Ho Hock Siang",:gender => "Male"
# Instructor.create! :name=> "Hong Kok Hua",:mobile=> "98733027",:email => "98733027@singaporeswimming.com",:password => "password",:short_name => "Hong Kok Hua",:gender => "Male"
# Instructor.create! :name=> "Huang Han Rong",:mobile=> "90288994",:email => "90288994@singaporeswimming.com",:password => "password",:short_name => "Huang Han Rong",:gender => "Male"
# Instructor.create! :name=> "Insanria Lee",:mobile=> "97627999",:email => "97627999@singaporeswimming.com",:password => "password",:short_name => "Ria Lee",:gender => "Female"
# Instructor.create! :name=> "Ishak",:mobile=> "91059386",:email => "91059386@singaporeswimming.com",:password => "password",:short_name => "Ishak",:gender => "Male"
# Instructor.create! :name=> "Ismail",:mobile=> "82183667",:email => "82183667@singaporeswimming.com",:password => "password",:short_name => "Ismail",:gender => "Male"
# Instructor.create! :name=> "Ivan",:mobile=> "98510763",:email => "98510763@singaporeswimming.com",:password => "password",:short_name => "Ivan",:gender => "Male"
# Instructor.create! :name=> "Ivan Tan wei Jian",:mobile=> "90227038",:email => "90227038@singaporeswimming.com",:password => "password",:short_name => "Ivan Tan wei Jian",:gender => "Male"
# Instructor.create! :name=> "James Wu",:mobile=> "96912587",:email => "96912587@singaporeswimming.com",:password => "password",:short_name => "James Wu",:gender => "Male"
# Instructor.create! :name=> "James(Toa Payoh)",:mobile=> "97565520",:email => "97565520@singaporeswimming.com",:password => "password",:short_name => "James",:gender => "Male"
# Instructor.create! :name=> "Jason",:mobile=> "97676655",:email => "97676655@singaporeswimming.com",:password => "password",:short_name => "Jason",:gender => "Male"
# Instructor.create! :name=> "Jason Ng Chee Guan",:mobile=> "90622601",:email => "90622601@singaporeswimming.com",:password => "password",:short_name => "Jason Ng Chee Guan",:gender => "Male"
# Instructor.create! :name=> "Jason Ng Cheng Kiat",:mobile=> "94853963",:email => "94853963@singaporeswimming.com",:password => "password",:short_name => "Jason Ng Cheng Kiat",:gender => "Male"
# Instructor.create! :name=> "Jee Wang",:mobile=> "97305201",:email => "97305201@singaporeswimming.com",:password => "password",:short_name => "Jee Wang",:gender => "Male"
# Instructor.create! :name=> "Jeffery Leong",:mobile=> "93887383",:email => "93887383@singaporeswimming.com",:password => "password",:short_name => "Jeffery Leong",:gender => "Male"
# Instructor.create! :name=> "Jeffery Lim",:mobile=> "97592834",:email => "97592834@singaporeswimming.com",:password => "password",:short_name => "Jeffery Lim",:gender => "Male"
# Instructor.create! :name=> "Jeffery Walter",:mobile=> "81392988",:email => "81392988@singaporeswimming.com",:password => "password",:short_name => "Jeffery Walter",:gender => "Male"
# Instructor.create! :name=> "Jennifer Tan",:mobile=> "96190630",:email => "96190630@singaporeswimming.com",:password => "password",:short_name => "Jennifer Tan",:gender => "Female"
# Instructor.create! :name=> "Jerald Lee",:mobile=> "97361825",:email => "97361825@singaporeswimming.com",:password => "password",:short_name => "Jerald",:gender => "Male"
# Instructor.create! :name=> "Jeremy CM",:mobile=> "97878989",:email => "97878989@singaporeswimming.com",:password => "password",:short_name => "Jeremy",:gender => "Male"
# Instructor.create! :name=> "Jeremy Phee",:mobile=> "97278822",:email => "97278822@singaporeswimming.com",:password => "password",:short_name => "Jeremy Phee",:gender => "Male"
# Instructor.create! :name=> "Jerry Koh",:mobile=> "83281754",:email => "83281754@singaporeswimming.com",:password => "password",:short_name => "Jerry Koh",:gender => "Male"
# Instructor.create! :name=> "Jessie Cheng",:mobile=> "91112175",:email => "91112175@singaporeswimming.com",:password => "password",:short_name => "Jessie Cheng",:gender => "Female"
# Instructor.create! :name=> "Jim Tan ",:mobile=> "83740203",:email => "83740203@singaporeswimming.com",:password => "password",:short_name => "Jim Tan",:gender => "Male"
# Instructor.create! :name=> "Jimmy Lee",:mobile=> "97523002",:email => "97523002@singaporeswimming.com",:password => "password",:short_name => "Jimmy Lee",:gender => "Male"
# Instructor.create! :name=> "Jimmy Tan",:mobile=> "90619928",:email => "90619928@singaporeswimming.com",:password => "password",:short_name => "Jimmy Tan",:gender => "Male"
# Instructor.create! :name=> "Joanne",:mobile=> "96692224",:email => "96692224@singaporeswimming.com",:password => "password",:short_name => "Joanne",:gender => "Female"
# Instructor.create! :name=> "Joe Chan",:mobile=> "97408887",:email => "97408887@singaporeswimming.com",:password => "password",:short_name => "Joe Chan",:gender => "Male"
# Instructor.create! :name=> "Joe Cheng",:mobile=> "90498560",:email => "90498560@singaporeswimming.com",:password => "password",:short_name => "Joe Cheng",:gender => "Male"
# Instructor.create! :name=> "Joe Ong ",:mobile=> "93820200",:email => "93820200@singaporeswimming.com",:password => "password",:short_name => "Joe Ong",:gender => "Male"
# Instructor.create! :name=> "Joey",:mobile=> "91116698",:email => "91116698@singaporeswimming.com",:password => "password",:short_name => "Joey",:gender => "Male"
# Instructor.create! :name=> "John Quek Wee Kok",:mobile=> "90608612",:email => "90608612@singaporeswimming.com",:password => "password",:short_name => "John Quek",:gender => "Male"
# Instructor.create! :name=> "John Teng",:mobile=> "81827095",:email => "81827095@singaporeswimming.com",:password => "password",:short_name => "John Teng",:gender => "Male"
# Instructor.create! :name=> "Johnny Lee",:mobile=> "92728246",:email => "92728246@singaporeswimming.com",:password => "password",:short_name => "Johnny Lee",:gender => "Male"
# Instructor.create! :name=> "Jonathan SK",:mobile=> "85006626",:email => "85006626@singaporeswimming.com",:password => "password",:short_name => "Jonathan",:gender => "Male"
# Instructor.create! :name=> "Jonathan Yiong Yong Sin",:mobile=> "90687666",:email => "90687666@singaporeswimming.com",:password => "password",:short_name => "Jonathan Yiong",:gender => "Male"
# Instructor.create! :name=> "Joseph Lian",:mobile=> "96788931",:email => "96788931@singaporeswimming.com",:password => "password",:short_name => "Joseph Lian",:gender => "Male"
# Instructor.create! :name=> "Joshua Chong",:mobile=> "97606985",:email => "97606985@singaporeswimming.com",:password => "password",:short_name => "Joshua Chong",:gender => "Male"
# Instructor.create! :name=> "Jun Da",:mobile=> "96454786",:email => "96454786@singaporeswimming.com",:password => "password",:short_name => "Jun Da",:gender => "Male"
# Instructor.create! :name=> "Kah Heng",:mobile=> "91285453",:email => "91285453@singaporeswimming.com",:password => "password",:short_name => "Kah Heng",:gender => "Male"
# Instructor.create! :name=> "Keith",:mobile=> "97598582",:email => "97598582@singaporeswimming.com",:password => "password",:short_name => "Keith",:gender => "Male"
# Instructor.create! :name=> "Kelvin Chong",:mobile=> "90999828",:email => "90999828@singaporeswimming.com",:password => "password",:short_name => "Kelvin Chong",:gender => "Male"
# Instructor.create! :name=> "Ken Siah Leong Kheng",:mobile=> "90951808",:email => "90951808@singaporeswimming.com",:password => "password",:short_name => "Ken Siah",:gender => "Male"
# Instructor.create! :name=> "Kenneth Koh",:mobile=> "98801049",:email => "98801049@singaporeswimming.com",:password => "password",:short_name => "Kenneth",:gender => "Male"
# Instructor.create! :name=> "Kenneth Toh",:mobile=> "93275758",:email => "93275758@singaporeswimming.com",:password => "password",:short_name => "Kenneth Toh",:gender => "Male"
# Instructor.create! :name=> "Kenny (JE JW)",:mobile=> "97934565",:email => "97934565@singaporeswimming.com",:password => "password",:short_name => "Kenny (JE JW)",:gender => "Male"
# Instructor.create! :name=> "Kenny Ang",:mobile=> "94318376",:email => "94318376@singaporeswimming.com",:password => "password",:short_name => "Kenny",:gender => "Male"
# Instructor.create! :name=> "Kenny Chan(GE)",:mobile=> "90055990",:email => "90055990@singaporeswimming.com",:password => "password",:short_name => "Kenny",:gender => "Male"
# Instructor.create! :name=> "Kenny Fong",:mobile=> "96848513",:email => "96848513@singaporeswimming.com",:password => "password",:short_name => "Kenny Fong",:gender => "Male"
# Instructor.create! :name=> "Kes Low",:mobile=> "96773858",:email => "96773858@singaporeswimming.com",:password => "password",:short_name => "Kes Low",:gender => "Male"
# Instructor.create! :name=> "Kevin (GE)",:mobile=> "94598881",:email => "94598881@singaporeswimming.com",:password => "password",:short_name => "Kevin (GE)",:gender => "Male"
# Instructor.create! :name=> "Khidir (Kid)",:mobile=> "96616071",:email => "96616071@singaporeswimming.com",:password => "password",:short_name => "Khidir (Kid)",:gender => "Male"
# Instructor.create! :name=> "Kian Hoe",:mobile=> "97929467",:email => "97929467@singaporeswimming.com",:password => "password",:short_name => "Kian Hoe",:gender => "Male"
# Instructor.create! :name=> "Kim Chow",:mobile=> "94350160",:email => "94350160@singaporeswimming.com",:password => "password",:short_name => "Kim Chow",:gender => "Male"
# Instructor.create! :name=> "Kim Hng Ngee",:mobile=> "96907234",:email => "96907234@singaporeswimming.com",:password => "password",:short_name => "Kim Hng Ngee",:gender => "Male"
# Instructor.create! :name=> "Kin Choon Nah",:mobile=> "97576516",:email => "97576516@singaporeswimming.com",:password => "password",:short_name => "Kin Choon Nah",:gender => "Male"
# Instructor.create! :name=> "Kit Yip",:mobile=> "90409198",:email => "90409198@singaporeswimming.com",:password => "password",:short_name => "Kit Yip",:gender => "Male"
# Instructor.create! :name=> "Koh Ah Leck",:mobile=> "98531844",:email => "98531844@singaporeswimming.com",:password => "password",:short_name => "Koh Ah Leck",:gender => "Male"
# Instructor.create! :name=> "Koh Kai Kia",:mobile=> "96617939",:email => "96617939@singaporeswimming.com",:password => "password",:short_name => "Koh Kai Kia",:gender => "Male"
# Instructor.create! :name=> "Kong Lye Loong",:mobile=> "97820352",:email => "97820352@singaporeswimming.com",:password => "password",:short_name => "Kong Lye Loong",:gender => "Male"
# Instructor.create! :name=> "Koo Nan Yong",:mobile=> "96323250",:email => "96323250@singaporeswimming.com",:password => "password",:short_name => "Koo Nan Yong",:gender => "Male"
# Instructor.create! :name=> "Kwa Chin Seng",:mobile=> "98328025",:email => "98328025@singaporeswimming.com",:password => "password",:short_name => "Kwa Chin Seng",:gender => "Male"
# Instructor.create! :name=> "Kwok Mei Yun",:mobile=> "94527653",:email => "94527653@singaporeswimming.com",:password => "password",:short_name => "Kwok Mei Yun",:gender => "Female"
# Instructor.create! :name=> "Lai Ghee Hong",:mobile=> "94379288",:email => "94379288@singaporeswimming.com",:password => "password",:short_name => "Lai Ghee Hong",:gender => "Male"
# Instructor.create! :name=> "Larry Chan Kwan Wee",:mobile=> "82335614",:email => "82335614@singaporeswimming.com",:password => "password",:short_name => "Larry Chan",:gender => "Male"
# Instructor.create! :name=> "Larry Han",:mobile=> "91768198",:email => "91768198@singaporeswimming.com",:password => "password",:short_name => "Larry Han",:gender => "Male"
# Instructor.create! :name=> "Lawrence Ang",:mobile=> "93231833",:email => "93231833@singaporeswimming.com",:password => "password",:short_name => "Lawrence Ang",:gender => "Male"
# Instructor.create! :name=> "Lee Chin Kuan ",:mobile=> "98580719",:email => "98580719@singaporeswimming.com",:password => "password",:short_name => "Lee Chin Kuan",:gender => "Male"
# Instructor.create! :name=> "Lee Peng Chua",:mobile=> "98383510",:email => "98383510@singaporeswimming.com",:password => "password",:short_name => "Lee Peng Chua",:gender => "Male"
# Instructor.create! :name=> "Li Jie",:mobile=> "96163331",:email => "96163331@singaporeswimming.com",:password => "password",:short_name => "Li Jie",:gender => "Male"
# Instructor.create! :name=> "Lim Jie Lun",:mobile=> "91114293",:email => "91114293@singaporeswimming.com",:password => "password",:short_name => "Lim Jie Lun",:gender => "Male"
# Instructor.create! :name=> "Lim Kim Hock",:mobile=> "98382950",:email => "98382950@singaporeswimming.com",:password => "password",:short_name => "Lim Kim Hock",:gender => "Male"
# Instructor.create! :name=> "Ling Yao Hui",:mobile=> "91011048",:email => "91011048@singaporeswimming.com",:password => "password",:short_name => "Ling Yao Hui",:gender => "Male"
# Instructor.create! :name=> "Lionel Loo",:mobile=> "97776962",:email => "97776962@singaporeswimming.com",:password => "password",:short_name => "Lionel Loo",:gender => "Male"
# Instructor.create! :name=> "Loke Lai Kwan",:mobile=> "96549901",:email => "96549901@singaporeswimming.com",:password => "password",:short_name => "Loke Lai Kwan",:gender => "Female"
# Instructor.create! :name=> "Long",:mobile=> "97431906",:email => "97431906@singaporeswimming.com",:password => "password",:short_name => "Long",:gender => "Male"
# Instructor.create! :name=> "Loo ",:mobile=> "97933211",:email => "97933211@singaporeswimming.com",:password => "password",:short_name => "Loo",:gender => "Male"
# Instructor.create! :name=> "Looi",:mobile=> "91143259",:email => "91143259@singaporeswimming.com",:password => "password",:short_name => "Mr Looi",:gender => "Male"
# Instructor.create! :name=> "Louis Lee",:mobile=> "98008856",:email => "98008856@singaporeswimming.com",:password => "password",:short_name => "Louis Lee",:gender => "Male"
# Instructor.create! :name=> "Louis Phua",:mobile=> "91018874",:email => "91018874@singaporeswimming.com",:password => "password",:short_name => "Louis Phua",:gender => "Male"
# Instructor.create! :name=> "Lum Kok Loong",:mobile=> "93398479",:email => "93398479@singaporeswimming.com",:password => "password",:short_name => "Lum Kok Loong",:gender => "Male"
# Instructor.create! :name=> "Mable",:mobile=> "97281235",:email => "97281235@singaporeswimming.com",:password => "password",:short_name => "Mable",:gender => "Female"
# Instructor.create! :name=> "Malcom Tan",:mobile=> "98187746",:email => "98187746@singaporeswimming.com",:password => "password",:short_name => "Malcom Tan",:gender => "Male"
# Instructor.create! :name=> "Malcom Toh (JW)",:mobile=> "97844760",:email => "97844760@singaporeswimming.com",:password => "password",:short_name => "Malcom Toh",:gender => "Male"
# Instructor.create! :name=> "Manfred Ng Wei Sheng",:mobile=> "90692102",:email => "90692102@singaporeswimming.com",:password => "password",:short_name => "Manfred Ng",:gender => "Male"
# Instructor.create! :name=> "Mark Wong",:mobile=> "98340167",:email => "98340167@singaporeswimming.com",:password => "password",:short_name => "Mark Wong",:gender => "Male"
# Instructor.create! :name=> "Maureen Lee",:mobile=> "93843535",:email => "93843535@singaporeswimming.com",:password => "password",:short_name => "Maureen Lee",:gender => "Female"
# Instructor.create! :name=> "Mei Yun",:mobile=> "83214589",:email => "83214589@singaporeswimming.com",:password => "password",:short_name => "Mei Yun",:gender => "Female"
# Instructor.create! :name=> "Mervyn",:mobile=> "96302657",:email => "96302657@singaporeswimming.com",:password => "password",:short_name => "Mervyn",:gender => "Male"
# Instructor.create! :name=> "Michael Tan",:mobile=> "81182667",:email => "81182667@singaporeswimming.com",:password => "password",:short_name => "Michael Tan",:gender => "Male"
# Instructor.create! :name=> "Mike Wong",:mobile=> "85717287",:email => "85717287@singaporeswimming.com",:password => "password",:short_name => "Mike Wong",:gender => "Male"
# Instructor.create! :name=> "Mogan",:mobile=> "90476114",:email => "90476114@singaporeswimming.com",:password => "password",:short_name => "Mogan",:gender => "Male"
# Instructor.create! :name=> "Mr Oh",:mobile=> "98247353",:email => "98247353@singaporeswimming.com",:password => "password",:short_name => "Mr Oh",:gender => "Male"
# Instructor.create! :name=> "Muhammad Ridhwan B Hussin",:mobile=> "82895685",:email => "82895685@singaporeswimming.com",:password => "password",:short_name => "Ridhwan",:gender => "Male"
# Instructor.create! :name=> "Nancy Loo",:mobile=> "98776849",:email => "98776849@singaporeswimming.com",:password => "password",:short_name => "Nancy",:gender => "Female"
# Instructor.create! :name=> "Neil Ong",:mobile=> "93896145",:email => "93896145@singaporeswimming.com",:password => "password",:short_name => "Neil Ong",:gender => "Male"
# Instructor.create! :name=> "Nelson Chin JW",:mobile=> "91515585",:email => "91515585@singaporeswimming.com",:password => "password",:short_name => "Nelson",:gender => "Male"
# Instructor.create! :name=> "Nelson Toh",:mobile=> "96816123",:email => "96816123@singaporeswimming.com",:password => "password",:short_name => "Nelson Toh",:gender => "Male"
# Instructor.create! :name=> "Neo Soon Seng",:mobile=> "92950669",:email => "92950669@singaporeswimming.com",:password => "password",:short_name => "Neo Soon Seng",:gender => "Male"
# Instructor.create! :name=> "Ng Sze Zeng",:mobile=> "97955098",:email => "97955098@singaporeswimming.com",:password => "password",:short_name => "Ng Sze Zeng",:gender => "Male"
# Instructor.create! :name=> "Nicky Sho",:mobile=> "97771447",:email => "97771447@singaporeswimming.com",:password => "password",:short_name => "Nicky Sho",:gender => "Male"
# Instructor.create! :name=> "Nina",:mobile=> "81187322",:email => "81187322@singaporeswimming.com",:password => "password",:short_name => "Nina",:gender => "Female"
# Instructor.create! :name=> "Ong Kai Quan",:mobile=> "97547076",:email => "97547076@singaporeswimming.com",:password => "password",:short_name => "Ong Kai Quan",:gender => "Male"
# Instructor.create! :name=> "Patrick Lee",:mobile=> "90042871",:email => "90042871@singaporeswimming.com",:password => "password",:short_name => "Patrick Lee",:gender => "Male"
# Instructor.create! :name=> "Patrick Ng",:mobile=> "90677450",:email => "90677450@singaporeswimming.com",:password => "password",:short_name => "Patrick Ng",:gender => "Male"
# Instructor.create! :name=> "Pattric Chua",:mobile=> "98911211",:email => "98911211@singaporeswimming.com",:password => "password",:short_name => "Pattric Chua",:gender => "Male"
# Instructor.create! :name=> "Penny Low",:mobile=> "94378277",:email => "94378277@singaporeswimming.com",:password => "password",:short_name => "Penny",:gender => "Female"
# Instructor.create! :name=> "Peter Chia",:mobile=> "97872950",:email => "97872950@singaporeswimming.com",:password => "password",:short_name => "Peter",:gender => "Male"
# Instructor.create! :name=> "Peter Wang",:mobile=> "90608309",:email => "90608309@singaporeswimming.com",:password => "password",:short_name => "Peter Wang",:gender => "Male"
# Instructor.create! :name=> "Philip Ong",:mobile=> "93399753",:email => "93399753@singaporeswimming.com",:password => "password",:short_name => "Philip Ong",:gender => "Male"
# Instructor.create! :name=> "Philip Soh",:mobile=> "96921965",:email => "96921965@singaporeswimming.com",:password => "password",:short_name => "Philip Soh",:gender => "Male"
# Instructor.create! :name=> "Ping",:mobile=> "97862179",:email => "97862179@singaporeswimming.com",:password => "password",:short_name => "Ping",:gender => "Female"
# Instructor.create! :name=> "Poh Leong Yee",:mobile=> "98355359",:email => "98355359@singaporeswimming.com",:password => "password",:short_name => "Poh Leong Yee",:gender => "Male"
# Instructor.create! :name=> "Prakash",:mobile=> "98755565",:email => "98755565@singaporeswimming.com",:password => "password",:short_name => "Prakash",:gender => "Male"
# Instructor.create! :name=> "Randy",:mobile=> "90237100",:email => "90237100@singaporeswimming.com",:password => "password",:short_name => "Randy",:gender => "Male"
# Instructor.create! :name=> "Ravi",:mobile=> "92384379",:email => "92384379@singaporeswimming.com",:password => "password",:short_name => "Ravi",:gender => "Male"
# Instructor.create! :name=> "Raymond Chiam",:mobile=> "92721215",:email => "92721215@singaporeswimming.com",:password => "password",:short_name => "Raymond",:gender => "Male"
# Instructor.create! :name=> "Raymond Ong",:mobile=> "93664542",:email => "93664542@singaporeswimming.com",:password => "password",:short_name => "Raymond Ong",:gender => "Male"
# Instructor.create! :name=> "Raymond Tan Kok Wah",:mobile=> "91375141",:email => "91375141@singaporeswimming.com",:password => "password",:short_name => "Raymond Tan",:gender => "Male"
# Instructor.create! :name=> "Reave Ng",:mobile=> "91510871",:email => "91510871@singaporeswimming.com",:password => "password",:short_name => "Reave Ng",:gender => "Male"
# Instructor.create! :name=> "Richard (Serangoon)",:mobile=> "90286118",:email => "90286118@singaporeswimming.com",:password => "password",:short_name => "Richard (Serangoon)",:gender => "Male"
# Instructor.create! :name=> "Richard Ho Weng Hei",:mobile=> "91780773",:email => "91780773@singaporeswimming.com",:password => "password",:short_name => "Richard Ho Weng Hei",:gender => "Male"
# Instructor.create! :name=> "Richard Lee",:mobile=> "96967717",:email => "96967717@singaporeswimming.com",:password => "password",:short_name => "Richard Lee",:gender => "Male"
# Instructor.create! :name=> "Richard Poh",:mobile=> "97543432",:email => "97543432@singaporeswimming.com",:password => "password",:short_name => "Richard Poh",:gender => "Male"
# Instructor.create! :name=> "Ricky Boo",:mobile=> "96844433",:email => "96844433@singaporeswimming.com",:password => "password",:short_name => "Ricky Boo",:gender => "Male"
# Instructor.create! :name=> "Rocky Sim Kim Yong",:mobile=> "96323291",:email => "96323291@singaporeswimming.com",:password => "password",:short_name => "Rocky Sim Kim Yong",:gender => "Male"
# Instructor.create! :name=> "Roger",:mobile=> "92952924",:email => "92952924@singaporeswimming.com",:password => "password",:short_name => "Roger",:gender => "Male"
# Instructor.create! :name=> "Rosie ",:mobile=> "94314831",:email => "94314831@singaporeswimming.com",:password => "password",:short_name => "Rosie",:gender => "Male"
# Instructor.create! :name=> "Royston",:mobile=> "98758050",:email => "98758050@singaporeswimming.com",:password => "password",:short_name => "Royston",:gender => "Male"
# Instructor.create! :name=> "Russell Wang",:mobile=> "92256924",:email => "92256924@singaporeswimming.com",:password => "password",:short_name => "Russell Wang",:gender => "Male"
# Instructor.create! :name=> "Ryan Yee",:mobile=> "98715557",:email => "98715557@singaporeswimming.com",:password => "password",:short_name => "Ryan Yee",:gender => "Male"
# Instructor.create! :name=> "Sally",:mobile=> "93887877",:email => "93887877@singaporeswimming.com",:password => "password",:short_name => "Sally",:gender => "Female"
# Instructor.create! :name=> "Sam (Salamat)",:mobile=> "93879321",:email => "93879321@singaporeswimming.com",:password => "password",:short_name => "Sam",:gender => "Male"
# Instructor.create! :name=> "Sam (YCK)",:mobile=> "92325236",:email => "92325236@singaporeswimming.com",:password => "password",:short_name => "Sam (YCK)",:gender => "Male"
# Instructor.create! :name=> "Sam Goh",:mobile=> "96170549",:email => "96170549@singaporeswimming.com",:password => "password",:short_name => "Sam Goh",:gender => "Male"
# Instructor.create! :name=> "Sam JW",:mobile=> "91730048",:email => "91730048@singaporeswimming.com",:password => "password",:short_name => "Sam",:gender => "Male"
# Instructor.create! :name=> "Seah Hock Heng",:mobile=> "96157451",:email => "96157451@singaporeswimming.com",:password => "password",:short_name => "Seah Hock Heng",:gender => "Male"
# Instructor.create! :name=> "Shau Soon Heng",:mobile=> "91518849",:email => "91518849@singaporeswimming.com",:password => "password",:short_name => "Shau Soon Heng",:gender => "Male"
# Instructor.create! :name=> "Shavin Tan",:mobile=> "92222236",:email => "92222236@singaporeswimming.com",:password => "password",:short_name => "Shavin Tan",:gender => "Female"
# Instructor.create! :name=> "Sim",:mobile=> "98382879",:email => "98382879@singaporeswimming.com",:password => "password",:short_name => "Sim",:gender => "Male"
# Instructor.create! :name=> "Sng Boon Seong",:mobile=> "98624281",:email => "98624281@singaporeswimming.com",:password => "password",:short_name => "Sng Boon Seong",:gender => "Male"
# Instructor.create! :name=> "Soh Kok Chye",:mobile=> "98570372",:email => "98570372@singaporeswimming.com",:password => "password",:short_name => "Soh Kok Chye",:gender => "Male"
# Instructor.create! :name=> "Stanley BB",:mobile=> "81831323",:email => "81831323@singaporeswimming.com",:password => "password",:short_name => "Stanley",:gender => "Male"
# Instructor.create! :name=> "Stanley Ng",:mobile=> "93668199",:email => "93668199@singaporeswimming.com",:password => "password",:short_name => "Stanley Ng",:gender => "Male"
# Instructor.create! :name=> "Steve Wong ",:mobile=> "96159167",:email => "96159167@singaporeswimming.com",:password => "password",:short_name => "Steve Wong",:gender => "Male"
# Instructor.create! :name=> "Steven Heng",:mobile=> "96436331",:email => "96436331@singaporeswimming.com",:password => "password",:short_name => "Steven Heng",:gender => "Male"
# Instructor.create! :name=> "Steven Lim",:mobile=> "93609822",:email => "93609822@singaporeswimming.com",:password => "password",:short_name => "Steven Lim",:gender => "Male"
# Instructor.create! :name=> "Steven Soon",:mobile=> "96571581",:email => "96571581@singaporeswimming.com",:password => "password",:short_name => "Steven Soon",:gender => "Male"
# Instructor.create! :name=> "Sunisa",:mobile=> "98509028",:email => "98509028@singaporeswimming.com",:password => "password",:short_name => "Sunisa",:gender => "Female"
# Instructor.create! :name=> "Sunny Loh Kia Loong",:mobile=> "96885085",:email => "96885085@singaporeswimming.com",:password => "password",:short_name => "Sunny Loh Kia Loong",:gender => "Male"
# Instructor.create! :name=> "Susan",:mobile=> "97661332",:email => "97661332@singaporeswimming.com",:password => "password",:short_name => "Susan",:gender => "Female"
# Instructor.create! :name=> "Taby",:mobile=> "90223804",:email => "90223804@singaporeswimming.com",:password => "password",:short_name => "Taby",:gender => "Female"
# Instructor.create! :name=> "Tan Chin Hoe",:mobile=> "96563325",:email => "96563325@singaporeswimming.com",:password => "password",:short_name => "Tan Chin Hoe",:gender => "Male"
# Instructor.create! :name=> "Tan Teow Hock",:mobile=> "96868460",:email => "96868460@singaporeswimming.com",:password => "password",:short_name => "Tan Teow Hock",:gender => "Male"
# Instructor.create! :name=> "Tan Thong Hua",:mobile=> "97678341",:email => "97678341@singaporeswimming.com",:password => "password",:short_name => "Tan Thong Hua",:gender => "Male"
# Instructor.create! :name=> "Tan Thong Tseng",:mobile=> "94559586",:email => "94559586@singaporeswimming.com",:password => "password",:short_name => "Tan Thong Tseng",:gender => "Male"
# Instructor.create! :name=> "Tan Xini",:mobile=> "98519671",:email => "98519671@singaporeswimming.com",:password => "password",:short_name => "Tan Xini",:gender => "Female"
# Instructor.create! :name=> "Tan Yee Min",:mobile=> "96345691",:email => "96345691@singaporeswimming.com",:password => "password",:short_name => "Tan Yee Min",:gender => "Male"
# Instructor.create! :name=> "Tay Cheng Guan",:mobile=> "96461813",:email => "96461813@singaporeswimming.com",:password => "password",:short_name => "Tay Cheng Guan",:gender => "Male"
# Instructor.create! :name=> "Tay Hong Seng",:mobile=> "84260993",:email => "84260993@singaporeswimming.com",:password => "password",:short_name => "Tay Hong Seng",:gender => "Male"
# Instructor.create! :name=> "Tay Leong Kiat",:mobile=> "96914033",:email => "96914033@singaporeswimming.com",:password => "password",:short_name => "Tay Leong Kiat",:gender => "Male"
# Instructor.create! :name=> "Teh Chong Yuen",:mobile=> "91126768",:email => "91126768@singaporeswimming.com",:password => "password",:short_name => "Teh Chong Yuen",:gender => "Male"
# Instructor.create! :name=> "Teo Chin Lor",:mobile=> "81101355",:email => "81101355@singaporeswimming.com",:password => "password",:short_name => "Teo Chin Lor",:gender => "Male"
# Instructor.create! :name=> "Teo Kim Chye",:mobile=> "92377430",:email => "92377430@singaporeswimming.com",:password => "password",:short_name => "Teo Kim Chye",:gender => "Male"
# Instructor.create! :name=> "Teo Kim Teck",:mobile=> "90629815",:email => "90629815@singaporeswimming.com",:password => "password",:short_name => "Teo Kim Teck",:gender => "Male"
# Instructor.create! :name=> "Terence Yeong",:mobile=> "97908803",:email => "97908803@singaporeswimming.com",:password => "password",:short_name => "Terence Yeong",:gender => "Male"
# Instructor.create! :name=> "Terrence Ang",:mobile=> "90927918",:email => "90927918@singaporeswimming.com",:password => "password",:short_name => "Terrence Ang",:gender => "Male"
# Instructor.create! :name=> "Terrence Kwa",:mobile=> "91703376",:email => "91703376@singaporeswimming.com",:password => "password",:short_name => "Terrence Kwa",:gender => "Male"
# Instructor.create! :name=> "Terrence Ng",:mobile=> "91805547",:email => "91805547@singaporeswimming.com",:password => "password",:short_name => "Terrence Ng",:gender => "Male"
# Instructor.create! :name=> "Terrence Tan (SPE)",:mobile=> "96709702",:email => "96709702@singaporeswimming.com",:password => "password",:short_name => "Terrence Tan",:gender => "Male"
# Instructor.create! :name=> "Terry",:mobile=> "93665846",:email => "93665846@singaporeswimming.com",:password => "password",:short_name => "Terry",:gender => "Male"
# Instructor.create! :name=> "Thomas Wong",:mobile=> "81820333",:email => "81820333@singaporeswimming.com",:password => "password",:short_name => "Thomas Wong",:gender => "Male"
# Instructor.create! :name=> "Tian Cai",:mobile=> "92953205",:email => "92953205@singaporeswimming.com",:password => "password",:short_name => "Tian Cai",:gender => "Male"
# Instructor.create! :name=> "Tobby",:mobile=> "91451491",:email => "91451491@singaporeswimming.com",:password => "password",:short_name => "Tobby",:gender => "Female"
# Instructor.create! :name=> "Val",:mobile=> "98535346",:email => "98535346@singaporeswimming.com",:password => "password",:short_name => "Val",:gender => "Female"
# Instructor.create! :name=> "Valerie",:mobile=> "91727573",:email => "91727573@singaporeswimming.com",:password => "password",:short_name => "Valerie",:gender => "Female"
# Instructor.create! :name=> "Victor",:mobile=> "83011383",:email => "83011383@singaporeswimming.com",:password => "password",:short_name => "Victor",:gender => "Male"
# Instructor.create! :name=> "Victor Tan",:mobile=> "96181867",:email => "96181867@singaporeswimming.com",:password => "password",:short_name => "Victor Tan",:gender => "Male"
# Instructor.create! :name=> "Victor Tay Chee Hiong",:mobile=> "81882321",:email => "81882321@singaporeswimming.com",:password => "password",:short_name => "Victor Tay Chee Hiong",:gender => "Male"
# Instructor.create! :name=> "Victor Tay Lip Seng",:mobile=> "97504097",:email => "97504097@singaporeswimming.com",:password => "password",:short_name => "Victor Tay Lip Seng",:gender => "Male"
# Instructor.create! :name=> "Vincent (CCK)",:mobile=> "83226771",:email => "83226771@singaporeswimming.com",:password => "password",:short_name => "Vincent",:gender => "Male"
# Instructor.create! :name=> "Vincent Soh Wei Yu",:mobile=> "98421315",:email => "98421315@singaporeswimming.com",:password => "password",:short_name => "Vincent Soh Wei Yu",:gender => "Male"
# Instructor.create! :name=> "vivien",:mobile=> "90622985",:email => "90622985@singaporeswimming.com",:password => "password",:short_name => "vivien",:gender => "Female"
# Instructor.create! :name=> "Wai Seng",:mobile=> "81270629",:email => "81270629@singaporeswimming.com",:password => "password",:short_name => "Wai Seng",:gender => "Male"
# Instructor.create! :name=> "Weiming",:mobile=> "98477451",:email => "98477451@singaporeswimming.com",:password => "password",:short_name => "Weiming",:gender => "Male"
# Instructor.create! :name=> "Willy Choo",:mobile=> "91012974",:email => "91012974@singaporeswimming.com",:password => "password",:short_name => "Willy Choo",:gender => "Male"
# Instructor.create! :name=> "Willy Liew",:mobile=> "98585686",:email => "98585686@singaporeswimming.com",:password => "password",:short_name => "Willy Liew",:gender => "Male"
# Instructor.create! :name=> "Wilson Ng",:mobile=> "98765751",:email => "98765751@singaporeswimming.com",:password => "password",:short_name => "Wilson Ng",:gender => "Male"
# Instructor.create! :name=> "Wong Chong Hoon",:mobile=> "91866709",:email => "91866709@singaporeswimming.com",:password => "password",:short_name => "Wong Chong Hoon",:gender => "Male"
# Instructor.create! :name=> "Wong Keng Tang",:mobile=> "98236944",:email => "98236944@singaporeswimming.com",:password => "password",:short_name => "Wong Keng Tang",:gender => "Male"
# Instructor.create! :name=> "Xavier Lau",:mobile=> "91766323",:email => "91766323@singaporeswimming.com",:password => "password",:short_name => "Xavier Lau",:gender => "Male"
# Instructor.create! :name=> "Xavier Song",:mobile=> "82182101",:email => "82182101@singaporeswimming.com",:password => "password",:short_name => "Xavier Song",:gender => "Male"
# Instructor.create! :name=> "Yap Beng Huat",:mobile=> "93851813",:email => "93851813@singaporeswimming.com",:password => "password",:short_name => "Yap Beng Huat",:gender => "Male"
# Instructor.create! :name=> "Yeo Nai Seng",:mobile=> "97317990",:email => "97317990@singaporeswimming.com",:password => "password",:short_name => "Yeo Nai Seng",:gender => "Male"
# Instructor.create! :name=> "Ying Jing",:mobile=> "96568791",:email => "96568791@singaporeswimming.com",:password => "password",:short_name => "Ying Jing",:gender => "Female"
# Instructor.create! :name=> "Yong Chong",:mobile=> "97564970",:email => "97564970@singaporeswimming.com",:password => "password",:short_name => "Yong Chong",:gender => "Male"
# Instructor.create! :name=> "Yong Quan",:mobile=> "93380853",:email => "93380853@singaporeswimming.com",:password => "password",:short_name => "Yong Quan",:gender => "Male"
# Instructor.create! :name=> "Yow Heng Kiong",:mobile=> "92707102",:email => "92707102@singaporeswimming.com",:password => "password",:short_name => "Yow",:gender => "Male"
# Instructor.create! :name=> "Zac Sok Leng",:mobile=> "96341117",:email => "96341117@singaporeswimming.com",:password => "password",:short_name => "Zac",:gender => "Male"
# Instructor.create! :name=> "Zhen Hao",:mobile=> "96985287",:email => "96985287@singaporeswimming.com",:password => "password",:short_name => "Zhen Hao",:gender => "Male"
# Instructor.create! :name=> "Zul",:mobile=> "97107361",:email => "97107361@singaporeswimming.com",:password => "password",:short_name => "Zul",:gender => "Male"
# puts "Instructor created successfully."
# # Coordinator.create! :name=> "Savan",:mobile=> "8460850591",:email => "savan@coordinator.com",:password => "admin123",:short_name => "Coordinator",:gender => "Male"
# Feature.create! feature_name: 'Reddot Visa/Master'
# Feature.create! feature_name: 'Reddot eNets'

# MoreOrLessMonth.where(table_name:'group_class').find_each do |m|
# 	if m.fee_attendance == 'fee_attendance'
# 		m.update_attributes(start_month_view_atte: m.start_month, end_month_view_atte: m.end_month)
# 	end
# end

StudentAttendance.all.each do |stu|
	date=stu.attendance_date+"-"+stu.created_at.strftime("%Y")
	date=date.to_date
	stu.update_attributes(attendance: date)
end